add homepage with all articles
gwdawson/northcoders-news-frontend pull request #1
Opened 2022-04-19 11:58 UTC by gwdawson

2022-04-19 13:48 UTC, jadelandeg commented on src/components/Articles.jsx
> +export default function Articles() {
why are you exporting this function?

2022-04-19 13:49 UTC, jadelandeg commented on src/components/Articles.jsx
> +      {articles.map((article) => (
each item in list needs a unique key

2022-04-19 13:52 UTC, jadelandeg commented on src/components/Articles.jsx
> +  const backend = axios.create({
will be reusing this a lot, would there be a better place to put it?

2022-04-20 08:59 UTC, gwdawson commented on src/components/Articles.jsx
> +export default function Articles() {
Articles needs to be exported so i can access it in App.jsx sorry you cant see where its being used i accidentally pushed the to main
```js
function App() {
  return (
    <div className='App'>
      <Nav />
      <Header />
      <Routes>
        <Route path='/' element={<Articles />}></Route>
      </Routes>
    </div>
  );
}
```

2022-04-20 09:16 UTC, karlaferry commented on src/utils/api.js
> +export const makeRequest = async (setArticles) => {
Everything looks good, however for api calls I would recommend you use function names that say what type of request you are doing. For this one, you can call it something like _getAllArticles_.

2022-04-20 09:18 UTC, gwdawson commented on src/utils/api.js
> +export const makeRequest = async (setArticles) => {
thank you ill get that changed now!

2022-04-20 09:18 UTC, karlaferry requested changes
Good job. Only comment is try to make the api call function names a bit more descriptive. :) CSS looks good!

2022-04-20 09:23 UTC, karlaferry approved these changes
Looks good! Approved :)

2022-04-20 09:25 UTC, merged