View separate page for each topic
gwdawson/northcoders-news-frontend pull request #2
Opened 2022-04-20 11:19 UTC by gwdawson

2022-04-20 11:34 UTC, karlaferry commented on src/components/Nav.jsx
> +      <Link className='NavChild' to='/topics/cooking'>
Honestly would suggest not hardcoding the topics like this and make it dynamic. If I remember correctly your backend should be able to serve just the list of topics, so you could make an API call to request all that.

2022-04-20 11:35 UTC, karlaferry requested changes
Make it more dynamic and account for the possibility of a user being able to add a new topic. :)

2022-04-21 09:56 UTC, jadelandeg commented on src/components/Header.jsx
> +  const newTopic = first + rest;
what are these variables for?

2022-04-21 09:57 UTC, jadelandeg requested changes
Looks really good! It looks like you have some unused variables. The first and rest ones. What are they doing?

2022-04-21 10:01 UTC, gwdawson commented on src/components/Header.jsx
> +  const newTopic = first + rest;
I'm sending `newTopic` on line 16.
this is just capitalising the first letter of the header.
`coding Articles` -> `Coding Articles`

2022-04-21 10:43 UTC, jadelandeg approved these changes

2022-04-21 10:43 UTC, merged